num_1 = int(input("Enter the 1st integer:"))
num_2 = int(input("Enter the 2st integer:"))
print("Addition =",num_1+num_2)
print("Subtraction =",num_1-num_2)
print("Multiplication =",num_1*num_2)
print("Division =",num_1//num_2)
print("Power =",num_1**num_2)
print("Modulus =",num_1%num_2)

num_1 = float(input("Enter the 1st number:"))
num_2 = float(input("Enter the 2st number:"))
print("Addition =",num_1+num_2)
print("Subtraction =",num_1-num_2)
print("Multiplication =",num_1*num_2)
print("Division =",num_1/num_2)
print("Power =",num_1**num_2)
print("Modulus =",num_1%num_2)